project:
  type: website
  output-dir: docs

website:
  title: "Pedoman Pelaksanaan Tugas Akhir, Tesis dan Disertasi"

  navbar:
      left:
        - href: index.qmd
          text: Home
        - href: rekayasa.qmd
          text: Rekayasa
        - href: inovasi.qmd
          text: Inovasi
        - href: invensi.qmd
          text: Invensi
        - href: temuan.qmd
          text: Temuan
        - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



