project:
  type: book
  output-dir: docs

book:
  title: "Pedoman"
  author: "Armein Z. R. Langi"
  date: "11/30/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - narasi.qmd
    - rekayasa.qmd
    - inovasi.qmd
    - invensi.qmd
    - temuan.qmd  
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: report



